import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from './../components/Navbar/Navbar';
import Layout from './../components/Layout/Layout';
import Header from './../components/Header/Header';
import About from './../components/About/About';


export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Adel Kouaou</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Navbar/>
    
      <Layout>
         <Header/>
         <About/>
      </Layout>

    </div>
  )
}
